# Generated by Django 4.0.6 on 2022-08-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark',
            field=models.BooleanField(default=False),
        ),
    ]
