# Generated by Django 4.0.6 on 2022-08-17 11:54

import about_me.validators
import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_dark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, upload_to=accounts.models.upload_location, validators=[about_me.validators.validate_file_size]),
        ),
    ]
