# Generated by Django 4.0.6 on 2022-08-09 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogname', models.CharField(max_length=100)),
                ('blogauth', models.CharField(max_length=100)),
                ('blogdes', models.TextField(max_length=400)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('blogcontent', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
