# Generated by Django 4.0.6 on 2022-08-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='img',
        ),
    ]
