# Generated by Django 4.0.6 on 2022-08-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='<django.db.models.fields.related.ForeignKey>/gallery'),
        ),
    ]
