# Generated by Django 4.0.6 on 2022-08-17 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photography.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photography', '0002_alter_image_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='img',
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=photography.models.upload_location),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='photography.collection'),
        ),
    ]
