# Generated by Django 4.0.6 on 2022-08-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_remove_image_uploaded_by_remove_photogallery_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='collection_summary',
        ),
        migrations.AddField(
            model_name='collection',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
