# Generated by Django 4.0.6 on 2022-08-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0009_alter_comment_author_alter_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text_content',
            field=models.TextField(blank=True),
        ),
    ]
